### ISSUE TITLE
Wallet not loaded yet!  

### ISSUE THREAD

**Issue by it-is-gut** [wearekite/candy-machine-v3-ui#9]
I cloned your repo and did the following changes: 
- Adapted .env file to match my deployed candy machine on devnet
- Adapted the mintGroups.json file to match my group labels

When i now run your UI locally, everything works expect I cannot mint. I have verified that the used wallet is in the guard group allowed to mint and I did not make any erros when generating the merkle root. 

When I check the error log, i see the following message: 
Error while fetching candy machine Error: Wallet not loaded yet!
 
![Bildschirm­foto 2023-04-29 um 17 45 53](https://user-images.githubusercontent.com/29917858/235311372-ea049924-48a3-44d9-ab6c-f46d254d4fd4.png)

What does this error message mean? The wallet is correctly connected in the GUI and the balance is also correctly displayed.

**Comment by wearekite** [comment]
Hey @it-is-gut,

Could you share your CMid & mint link with me so I can replicate your issue.

You can also email it to me if you prefer. My email is hello@kite.studio

**Comment by wearekite** [comment]
The wallet not loaded error is a default error callback. The page takes a little while to load and the console logs everything, the wallet is properly loaded in a later log with `console.log("useEffact([mx, wallet.publicKey])");`

For reference to the error callbacks head to file: useCandyMachineV3.tsx, line:133 & line:298.

The core of this issue is the same as Issue #7, the use of a newer account version that is not yet supported by this UI.
Using [sugar v2.0.0-beta.2](https://github.com/metaplex-foundation/sugar/releases/tag/v2.0.0-beta.2) to deploy your CM would resolve this.
